### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by stsewd** [pythonecuador/lira#17]
Badges from:

- https://readthedocs.org/projects/lira/
- https://codecov.io/gh/pythonecuador/lira/
- https://github.com/pythonecuador/lira/actions
- https://pypi.org/project/lira/

**Comment by rpalaciosg** [comment]
Hola, puedo trabajar en este issue, solo para estar seguro, es esto lo que se necesita:

> https://readthedocs.org/projects/lira/
[![Documentation Status](https://readthedocs.org/projects/lira/badge/?version=latest)](https://lira.python.ec/en/latest/?badge=latest)

> https://codecov.io/gh/pythonecuador/lira/
![codecov.io](https://codecov.io/github/pythonecuador/lira/coverage.svg?branch=master)
(https://codecov.io/github/<Your Organization/Acc.>/<YourRepo>?branch=master)

> https://github.com/pythonecuador/lira/actions
![tests](https://github.com/pythonecuador/lira/workflows/tests/badge.svg)

> https://pypi.org/project/lira/
[![PyPI version](https://badge.fury.io/py/lira.svg)](https://badge.fury.io/py/lira)

**Comment by stsewd** [comment]
@rpalaciosg si! justo eso. El badge de githun actions debe apuntar a https://github.com/pythonecuador/lira/actions?query=workflow%3Atests+branch%3Amaster

**Comment by rpalaciosg** [comment]
esto iria al inicio en el README.md?

**Comment by stsewd** [comment]
Si, justo debajo del primer título
