### ISSUE TITLE
Change one word on development.rst

### ISSUE THREAD

**Issue by Seburath** [pythonecuador/lira#49]
I forgot to add this suggestion to the merge.

https://github.com/pythonecuador/lira/pull/47#discussion_r509839072

Just one-word change issue.

**Comment by csampedroc** [comment]
I only need change "get" for "become" ?

**Comment by stsewd** [comment]
> I only need change "get" for "become" ?

yep!

**Comment by csampedroc** [comment]
Thanks!, I'm sending pull request.
