### ISSUE TITLE
Raise a warning when finding invalid nodes

### ISSUE THREAD

**Issue by stsewd** [pythonecuador/lira#59]
We only support a subset of nodes from rst. We should raise a warning if we find nodes that aren't recognized.

https://github.com/pythonecuador/lira/blob/7eccc4babc64da02ee88bbde5b9c386e961a81c2/lira/parsers/rst.py#L126-L142

**Comment by josselineperdomo** [comment]
Hello! I would like to work on this issue. Is a node invalid when it doesn't fit with any of the `directive_name` and is not part of `terminal_nodes` and `container_nodes`?

**Comment by stsewd** [comment]
@josselineperdomo yes, that's!

**Comment by josselineperdomo** [comment]
Could you please assign me this issue? :)

**Comment by stsewd** [comment]
Done, but just feel free to say you are solving this issue and send the PR, no need for assignments
