### ISSUE TITLE
Versiones de python soportadas

### ISSUE THREAD

**Issue by stsewd** [pythonecuador/lira#8]
Creo que estamos apuntando a python 3.6 pa arriba. Pero debemos verificar que las dependencias que usemos soporten esas versiones.

**Comment by Danielrick88** [comment]
Usemos la 3.9 y le ponemos una guía en python.ec de como actualizar. Despues de todo las versiones anteriores van quedando end-of-life.

**Comment by stsewd** [comment]
Planeamos soportar desde la 3.7 en adelante.
